// 389. Find the Difference
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

class Solution {
    public char findTheDifference(String s, String t) {
        
        char[] ca1= s.toCharArray();
        char[] ca2= t.toCharArray();

        Arrays.sort(ca1);
        Arrays.sort(ca2);
        for(int i=0;i<ca1.length;i++){
            if(ca1[i] != ca2[i]) return ca2[i];
        }
        return ca2[ca2.length-1];
    }
}